export const COUNTRIES_EN: Record<string, string> = {
  Afghanistan: 'AF',
  Albania: 'AL',
  Algeria: 'DZ',
  'American Samoa': 'AS',
  Andorra: 'AD',
  Angola: 'AO',
  Anguilla: 'AI',
  Antarctica: 'AQ',
  'Antigua and Barbuda': 'AG',
  Argentina: 'AR',
  Armenia: 'AM',
  Aruba: 'AW',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaijan: 'AZ',
  Bahamas: 'BS',
  Bahrain: 'BH',
  Bangladesh: 'BD',
  Barbados: 'BB',
  Belarus: 'BY',
  Belgium: 'BE',
  Belize: 'BZ',
  Benin: 'BJ',
  Bermuda: 'BM',
  Bhutan: 'BT',
  Bolivia: 'BO',
  'Bosnia and Herzegovina': 'BA',
  Botswana: 'BW',
  'Bouvet Island': 'BV',
  Brazil: 'BR',
  'British Indian Ocean Territory': 'IO',
  'Brunei Darussalam': 'BN',
  Bulgaria: 'BG',
  'Burkina Faso': 'BF',
  Burundi: 'BI',
  Cambodia: 'KH',
  Cameroon: 'CM',
  Canada: 'CA',
  'Cape Verde': 'CV',
  'Cayman Islands': 'KY',
  'Central African Republic': 'CF',
  Chad: 'TD',
  Chile: 'CL',
  China: 'CN',
  'Christmas Island': 'CX',
  'Cocos (Keeling) Islands': 'CC',
  Colombia: 'CO',
  Comoros: 'KM',
  Congo: 'CG',
  'Congo, Democratic Republic': 'CD',
  'Cook Islands': 'CK',
  'Costa Rica': 'CR',
  "Cote D'Ivoire": 'CI',
  Croatia: 'HR',
  Cuba: 'CU',
  Cyprus: 'CY',
  'Czech Republic': 'CZ',
  Denmark: 'DK',
  Djibouti: 'DJ',
  Dominica: 'DM',
  'Dominican Republic': 'DO',
  Ecuador: 'EC',
  Egypt: 'EG',
  'El Salvador': 'SV',
  'Equatorial Guinea': 'GQ',
  Eritrea: 'ER',
  Estonia: 'EE',
  Ethiopia: 'ET',
  'Falkland Islands (Malvinas)': 'FK',
  'Faroe Islands': 'FO',
  Fiji: 'FJ',
  Finland: 'FI',
  France: 'FR',
  'French Guiana': 'GF',
  'French Polynesia': 'PF',
  'French Southern Territories': 'TF',
  Gabon: 'GA',
  Gambia: 'GM',
  Georgia: 'GE',
  Germany: 'DE',
  Ghana: 'GH',
  Gibraltar: 'GI',
  Greece: 'GR',
  Greenland: 'GL',
  Grenada: 'GD',
  Guadeloupe: 'GP',
  Guam: 'GU',
  Guatemala: 'GT',
  Guinea: 'GN',
  'Guinea-Bissau': 'GW',
  Guyana: 'GY',
  Haiti: 'HT',
  'Heard Island and Mcdonald Islands': 'HM',
  'Holy See (Vatican City State)': 'VA',
  Honduras: 'HN',
  'Hong Kong': 'HK',
  Hungary: 'HU',
  Iceland: 'IS',
  India: 'IN',
  Indonesia: 'ID',
  'Iran, Islamic Republic Of': 'IR',
  Iraq: 'IQ',
  Ireland: 'IE',
  Israel: 'IL',
  Italy: 'IT',
  Jamaica: 'JM',
  Japan: 'JP',
  Jordan: 'JO',
  Kazakhstan: 'KZ',
  Kenya: 'KE',
  Kiribati: 'KI',
  "Korea, Democratic People's Republic": 'KP',
  'Korea, Republic of': 'KR',
  Kuwait: 'KW',
  Kyrgyzstan: 'KG',
  "Lao People's Democratic Republic": 'LA',
  Latvia: 'LV',
  Lebanon: 'LB',
  Lesotho: 'LS',
  Liberia: 'LR',
  'Libyan Arab Jamahiriya': 'LY',
  Liechtenstein: 'LI',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  Macao: 'MO',
  'Macedonia, the Former Yugoslav Republic': 'MK',
  Madagascar: 'MG',
  Malawi: 'MW',
  Malaysia: 'MY',
  Maldives: 'MV',
  Mali: 'ML',
  Malta: 'MT',
  'Marshall Islands': 'MH',
  Martinique: 'MQ',
  Mauritania: 'MR',
  Mauritius: 'MU',
  Mayotte: 'YT',
  Mexico: 'MX',
  'Micronesia, Federated States': 'FM',
  'Moldova, Republic of': 'MD',
  Monaco: 'MC',
  Mongolia: 'MN',
  Montserrat: 'MS',
  Morocco: 'MA',
  Mozambique: 'MZ',
  Myanmar: 'MM',
  Namibia: 'NA',
  Nauru: 'NR',
  Nepal: 'NP',
  Netherlands: 'NL',
  'Netherlands Antilles': 'AN',
  'New Caledonia': 'NC',
  'New Zealand': 'NZ',
  Nicaragua: 'NI',
  Niger: 'NE',
  Nigeria: 'NG',
  Niue: 'NU',
  'Norfolk Island': 'NF',
  'Northern Mariana Islands': 'MP',
  Norway: 'NO',
  Oman: 'OM',
  Pakistan: 'PK',
  Palau: 'PW',
  'Palestinian Territory, Occupied': 'PS',
  Panama: 'PA',
  'Papua New Guinea': 'PG',
  Paraguay: 'PY',
  Peru: 'PE',
  Philippines: 'PH',
  Pitcairn: 'PN',
  Poland: 'PL',
  Portugal: 'PT',
  'Puerto Rico': 'PR',
  Qatar: 'QA',
  Reunion: 'RE',
  Romania: 'RO',
  'Russian Federation': 'RU',
  Rwanda: 'RW',
  'Saint Helena': 'SH',
  'Saint Kitts and Nevis': 'KN',
  'Saint Lucia': 'LC',
  'Saint Pierre and Miquelon': 'PM',
  'Saint Vincent and the Grenadines': 'VC',
  Samoa: 'WS',
  'San Marino': 'SM',
  'Sao Tome and Principe': 'ST',
  'Saudi Arabia': 'SA',
  Senegal: 'SN',
  Seychelles: 'SC',
  'Sierra Leone': 'SL',
  Singapore: 'SG',
  Slovakia: 'SK',
  Slovenia: 'SI',
  'Solomon Islands': 'SB',
  Somalia: 'SO',
  'South Africa': 'ZA',
  'South Georgia and the South Sandwich Islands': 'GS',
  Spain: 'ES',
  'Sri Lanka': 'LK',
  Sudan: 'SD',
  Suriname: 'SR',
  'Svalbard and Jan Mayen': 'SJ',
  Swaziland: 'SZ',
  Sweden: 'SE',
  Switzerland: 'CH',
  'Syrian Arab Republic': 'SY',
  'Taiwan, Province of China': 'TW',
  Tajikistan: 'TJ',
  'Tanzania, United Republic of': 'TZ',
  Thailand: 'TH',
  'Timor-Leste': 'TL',
  Togo: 'TG',
  Tokelau: 'TK',
  Tonga: 'TO',
  'Trinidad and Tobago': 'TT',
  Tunisia: 'TN',
  Turkey: 'TR',
  Turkmenistan: 'TM',
  'Turks and Caicos Islands': 'TC',
  Tuvalu: 'TV',
  Uganda: 'UG',
  Ukraine: 'UA',
  'United Arab Emirates': 'AE',
  'United Kingdom': 'GB',
  'United States': 'US',
  'United States Minor Outlying Islands': 'UM',
  Uruguay: 'UY',
  Uzbekistan: 'UZ',
  Vanuatu: 'VU',
  Venezuela: 'VE',
  'Viet Nam': 'VN',
  'Virgin Islands, British': 'VG',
  'Virgin Islands, U.S.': 'VI',
  'Wallis and Futuna': 'WF',
  'Western Sahara': 'EH',
  Yemen: 'YE',
  Zambia: 'ZM',
  Zimbabwe: 'ZW',
};

export const COUNTRIES_RU: Record<string, string> = {
  'Афганистан': 'AF',
  'Албания': 'AL',
  'Алжир': 'DZ',
  'Американское Самоа': 'AS',
  'Андорра': 'AD',
  'Ангола': 'AO',
  'Ангилья': 'AI',
  'Антарктида': 'AQ',
  'Антигуа и Барбуда': 'AG',
  'Аргентина': 'AR',
  'Армения': 'AM',
  'Аруба': 'AW',
  'Австралия': 'AU',
  'Австрия': 'AT',
  'Азербайджан': 'AZ',
  'Багамы': 'BS',
  'Бахрейн': 'BH',
  'Бангладеш': 'BD',
  'Барбадос': 'BB',
  'Беларусь': 'BY',
  'Бельгия': 'BE',
  'Белиз': 'BZ',
  'Бенин': 'BJ',
  'Бермуды': 'BM',
  'Бутан': 'BT',
  'Боливия': 'BO',
  'Босния и Герцеговина': 'BA',
  'Ботсвана': 'BW',
  'Остров Буве': 'BV',
  'Бразилия': 'BR',
  'Британская территория в Индийском океане': 'IO',
  'Бруней': 'BN',
  'Болгария': 'BG',
  'Буркина-Фасо': 'BF',
  'Бурунди': 'BI',
  'Камбоджа': 'KH',
  'Камерун': 'CM',
  'Канада': 'CA',
  'Кабо-Верде': 'CV',
  'Острова Кайман': 'KY',
  'ЦАР': 'CF',
  'Чад': 'TD',
  'Чили': 'CL',
  'Китай': 'CN',
  'Остров Рождества': 'CX',
  'Кокосовые острова': 'CC',
  'Колумбия': 'CO',
  'Коморы': 'KM',
  'Конго': 'CG',
  'ДР Конго': 'CD',
  'Острова Кука': 'CK',
  'Коста-Рика': 'CR',
  'Кот-д’Ивуар': 'CI',
  'Хорватия': 'HR',
  'Куба': 'CU',
  'Кипр': 'CY',
  'Чехия': 'CZ',
  'Дания': 'DK',
  'Джибути': 'DJ',
  'Доминика': 'DM',
  'Доминикана': 'DO',
  'Эквадор': 'EC',
  'Египет': 'EG',
  'Сальвадор': 'SV',
  'Экваториальная Гвинея': 'GQ',
  'Эритрея': 'ER',
  'Эстония': 'EE',
  'Эфиопия': 'ET',
  'Фолклендские острова': 'FK',
  'Фареры': 'FO',
  'Фиджи': 'FJ',
  'Финляндия': 'FI',
  'Франция': 'FR',
  'Французская Гвиана': 'GF',
  'Французская Полинезия': 'PF',
  'Французские Южные территории': 'TF',
  'Габон': 'GA',
  'Гамбия': 'GM',
  'Грузия': 'GE',
  'Германия': 'DE',
  'Гана': 'GH',
  'Гибралтар': 'GI',
  'Греция': 'GR',
  'Гренландия': 'GL',
  'Гренада': 'GD',
  'Гваделупа': 'GP',
  'Гуам': 'GU',
  'Гватемала': 'GT',
  'Гвинея': 'GN',
  'Гвинея-Бисау': 'GW',
  'Гайана': 'GY',
  'Гаити': 'HT',
  'Острова Херд и Макдональд': 'HM',
  'Ватикан': 'VA',
  'Гондурас': 'HN',
  'Гонконг': 'HK',
  'Венгрия': 'HU',
  'Исландия': 'IS',
  'Индия': 'IN',
  'Индонезия': 'ID',
  'Иран': 'IR',
  'Ирак': 'IQ',
  'Ирландия': 'IE',
  'Израиль': 'IL',
  'Италия': 'IT',
  'Ямайка': 'JM',
  'Япония': 'JP',
  'Иордания': 'JO',
  'Казахстан': 'KZ',
  'Кения': 'KE',
  'Кирибати': 'KI',
  'КНДР': 'KP',
  'Южная Корея': 'KR',
  'Кувейт': 'KW',
  'Киргизия': 'KG',
  'Лаос': 'LA',
  'Латвия': 'LV',
  'Ливан': 'LB',
  'Лесото': 'LS',
  'Либерия': 'LR',
  'Ливия': 'LY',
  'Лихтенштейн': 'LI',
  'Литва': 'LT',
  'Люксембург': 'LU',
  'Макао': 'MO',
  'Северная Македония': 'MK',
  'Мадагаскар': 'MG',
  'Малави': 'MW',
  'Малайзия': 'MY',
  'Мальдивы': 'MV',
  'Мали': 'ML',
  'Мальта': 'MT',
  'Маршалловы Острова': 'MH',
  'Мартиника': 'MQ',
  'Мавритания': 'MR',
  'Маврикий': 'MU',
  'Майотта': 'YT',
  'Мексика': 'MX',
  'Микронезия': 'FM',
  'Молдова': 'MD',
  'Монако': 'MC',
  'Монголия': 'MN',
  'Монтсеррат': 'MS',
  'Марокко': 'MA',
  'Мозамбик': 'MZ',
  'Мьянма': 'MM',
  'Намибия': 'NA',
  'Науру': 'NR',
  'Непал': 'NP',
  'Нидерланды': 'NL',
  'Нидерландские Антилы': 'AN',
  'Новая Каледония': 'NC',
  'Новая Зеландия': 'NZ',
  'Никарагуа': 'NI',
  'Нигер': 'NE',
  'Нигерия': 'NG',
  'Ниуэ': 'NU',
  'Остров Норфолк': 'NF',
  'Северные Марианские острова': 'MP',
  'Норвегия': 'NO',
  'Оман': 'OM',
  'Пакистан': 'PK',
  'Палау': 'PW',
  'Палестина': 'PS',
  'Панама': 'PA',
  'Папуа — Новая Гвинея': 'PG',
  'Парагвай': 'PY',
  'Перу': 'PE',
  'Филиппины': 'PH',
  'Питкэрн': 'PN',
  'Польша': 'PL',
  'Португалия': 'PT',
  'Пуэрто-Рико': 'PR',
  'Катар': 'QA',
  'Реюньон': 'RE',
  'Румыния': 'RO',
  'Россия': 'RU',
  'Руанда': 'RW',
  'Острова Святой Елены': 'SH',
  'Сент-Китс и Невис': 'KN',
  'Сент-Люсия': 'LC',
  'Сен-Пьер и Микелон': 'PM',
  'Сент-Винсент и Гренадины': 'VC',
  'Самоа': 'WS',
  'Сан-Марино': 'SM',
  'Сан-Томе и Принсипи': 'ST',
  'Саудовская Аравия': 'SA',
  'Сенегал': 'SN',
  'Сейшелы': 'SC',
  'Сьерра-Леоне': 'SL',
  'Сингапур': 'SG',
  'Словакия': 'SK',
  'Словения': 'SI',
  'Соломоновы Острова': 'SB',
  'Сомали': 'SO',
  'ЮАР': 'ZA',
  'Южная Георгия и Южные Сандвичевы острова': 'GS',
  'Испания': 'ES',
  'Шри-Ланка': 'LK',
  'Судан': 'SD',
  'Суринам': 'SR',
  'Шпицберген и Ян-Майен': 'SJ',
  'Эсватини': 'SZ',
  'Швеция': 'SE',
  'Швейцария': 'CH',
  'Сирия': 'SY',
  'Тайвань': 'TW',
  'Таджикистан': 'TJ',
  'Танзания': 'TZ',
  'Таиланд': 'TH',
  'Восточный Тимор': 'TL',
  'Того': 'TG',
  'Токелау': 'TK',
  'Тонга': 'TO',
  'Тринидад и Тобаго': 'TT',
  'Тунис': 'TN',
  'Турция': 'TR',
  'Туркменистан': 'TM',
  'Острова Тёркс и Кайкос': 'TC',
  'Тувалу': 'TV',
  'Уганда': 'UG',
  'Украина': 'UA',
  'ОАЭ': 'AE',
  'Великобритания': 'GB',
  'США': 'US',
  'Малые Тихоокеанские отдаленные острова США': 'UM',
  'Уругвай': 'UY',
  'Узбекистан': 'UZ',
  'Вануату': 'VU',
  'Венесуэла': 'VE',
  'Вьетнам': 'VN',
  'Британские Виргинские острова': 'VG',
  'Виргинские Острова (США)': 'VI',
  'Уоллис и Футуна': 'WF',
  'Западная Сахара': 'EH',
  'Йемен': 'YE',
  'Замбия': 'ZM',
  'Зимбабве': 'ZW'
};
